dist: trusty
sudo: false

language:
  - cpp

addons:
  apt:
    packages:
    - gperf

script:
  - make test/xtensa-esp32-elf test/esp-idf
  - pip install --user -r test/esp-idf/requirements.txt
  - make build
